name: swizz540.github.io

registries:

ships:
  localhost:
    ip: 127.0.0.1
    docker_port: 4243

services:
  jekyll:
    image: grahamc/jekyll:latest

    instances:
      swizz.github.io:
        command: "serve -w"
        ship: localhost
        ports: {http: 4000}
        volumes:
          /src: /home/swizz/Works/swizz540.github.io
